listProperty=[
    "Convert",
    "Sáng tác",
]
listOfType=[

    "Tiên Hiệp",
    "Kiếm Hiệp",
    "Đô Thị",
    "Huyền Ảo",
    "Ngôn Tình",
    "Dị Năng",
    "Võng Du",
    "Dị Giới",
    "Khoa Huyễn",
    "Quân Sự",
    "Lịch Sử",
    "Xuyên Không",
    "Trùng Sinh",
    "Cạnh Kỹ",
    "Đồng Nhân",
    "Linh Dị",
    "Mạt Thế",
    "Nữ Hiệp",
]
listStatus=[

    "Đang ra",
    "Hoàn thành",
]
listNumberChap=[
    "&lt; 100",
    "100-300",
    "300-600",
    "600-1000",
    "&gt; 1000",
]

listPostNearly=[
    "Khoảng ba ngày",
    "Khoảng một tuần",
    "Khoảng nữa tháng",
    "Khoảng một tháng",
]

listLabel = [
  "Bác Sĩ",
  "Bàn Tử",
  "Bao Che Khuyết Điểm",
  "Bỉ Ổi",
  "Biến Thân",
  "Bình Tĩnh",
  "Binh Vương",
  "Boss Lưu",
  "Chăm Chỉ",
  "Chính Đạo",
  "Chơi Xấu",
  "Chung Thủy",
  "Chủng Điền",
  "Cơ Giới",
  "Cô Nhi",
  "Cơ Trí",
  "Cổ Xuyên Kim",
  "Cổ Đại",
  "Cơm Chùa Lưu",
  "Công Sở",
  "Cung Đấu",
  "Cười Vang",
  "Cường Giả Trở Về",
  "Cường Hào Đoạt Thủ",
  "Cương Thi",
  "Cuồng Tu",
  "Dị Thú Lưu",
  "Dốc Lòng Nhân Sinh",
  "Dũng Mãnh",
  "Game Mobile",
  "Game Online",
  "Giám Bảo",
  "Giảo Hoạt",
  "Gien",
  "Giới Giải Trí",
  "Gương Vỡ Lại Lành",
  "Hắc Thủ",
  "Hacker",
  "Hào Môn",
  "Hào Môn Thế Gia",
  "Hấp Huyết Quỷ",
  "Hậu Cung",
  "Hệ Thống",
  "Hiện Thực",
  "Hiện Đại",
  "Học Sinh",
  "Học Viện Lưu",
  "Hồng Hoang Lưu",
  "Hương Thổ",
  "Huyền Học",
  "Huyền Huyễn Ma Pháp",
  "Huyền Huyễn Võng Du",
  "Khách Sạn",
  "Khát Máu",
  "Khởi Điểm",
  "Kiếm Tiền",
  "Kiên Nghị",
  "Kim Xuyên Cổ",
  "Kinh Doanh",
  "Kỹ Thuật Lưu",
  "Lãnh Khốc",
  "Lão Sư",
  "LOL",
  "Long",
  "Luyện Công Lưu",
  "Ma Thú",
  "Ma Vương Phụ Thể",
  "Mangaka",
  "Mary Sue",
  "Mỹ Thực",
  "Ngôi Sao",
  "Ngọt Sủng",
  "Ngược Nam",
  "Ngược Nữ",
  "Ngược Tra",
  "Ngược Văn",
  "Nhân Duyên Tiền Định",
  "Nhị Thứ Nguyên",
  "Nhiệt Huyết",
  "Nhóm Xuyên",
  "Nữ Cường",
  "Nữ Phụ",
  "Nữ Sinh",
  "Nữ Tôn",
  "Phách Lối",
  "Phàm Nhân Lưu",
  "Pháo Hôi",
  "Pháp Sư",
  "Phế Vật Lưu",
  "Phương Đông Huyền Huyễn",
  "Quỷ Quái",
  "Sáng Thế Chủ Thần",
  "Sảng Văn",
  "Sát Thủ",
  "Sủng Vật",
  "Tấn Giang",
  "Tang Thi",
  "Tây Du Ký",
  "Tây Phương Kỳ Huyễn",
  "Thần Quái",
  "Thanh Mai Trúc Mã",
  "Thanh Xuân Vườn Trường",
  "Thanh Xuyên",
  "Thẻ Bài",
  "Thiết Huyết",
  "Thoải Mái",
  "Tiểu Bạch",
  "Tinh Anh",
  "Tình Cảm",
  "Tình Hữu Độc Chung",
  "Tống Mạn",
  "Trạch Nam",
  "Trạch Đấu",
  "Trận Pháp",
  "Trang Bức",
  "Tranh Bá Lưu",
  "Triệu Hoán Lưu",
  "Trinh Thám",
  "Trọng Sinh",
  "Tương Lai",
  "Tùy Thân Lưu",
  "Tỷ Đệ Luyến",
  "Vả Mặt",
  "Vị Diện Lưu",
  "Viết Tiểu Thuyết",
  "Vô Hạn Lưu",
  "Vô Địch Văn",
  "Xấu Bụng",
  "Xuyên Chậm",
  "Xuyên Nhanh",
  "Xuyên Sách",
  "Xuyên Việt",
  "Zombie",
  "Đặc Công",
  "Đan Dược",
  "Đào Mộ",
  "Đạo Tặc",
  "Đổ Thạch",
  "Đô Thị Dị Năng",
  "Đô Thị Sinh Hoạt",
  "Đô Thị Tu Tiên",
  "Đô Thị Võng Du",
];
function createElementBtn(array, block){
    array.forEach((element) => {
        button = document.createElement("button");
        button.innerHTML = element;
        button.className = "btn--cate";
        block.appendChild(button);
      });
    return block;
  }


let blockLabel = document.querySelector(".label-block");
let blockPostNearly= document.querySelector(".postNearly-block");
let blockNumberChap = document.querySelector(".numberChap-block");
let blockStatus  = document.querySelector(".status-block");
let blockType = document.querySelector(".type-block");
let blockProperty = document.querySelector(".property-block");

createElementBtn(listLabel,blockLabel);
createElementBtn(listPostNearly,blockPostNearly);
createElementBtn(listNumberChap,blockNumberChap);
createElementBtn(listStatus,blockStatus);
createElementBtn(listOfType,blockType);
createElementBtn(listProperty,blockProperty);

